### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prathikshetty/video-tester#10]
```
What steps will reproduce the problem?
1. I installed video-tester and when I try to run it for the first time, using 
VT at the terminal I get the following error " Cannot assign requested address "
2.
3.

What is the expected output? What do you see instead?
get to see video-tester up and running.

What version of the product are you using? On what operating system?
video-tester 0.2 on Ubuntu 13.10

Please provide any additional information below.

pavan@pavan-Inspiron-5520:~/VideoTester-0.2$ VT
Traceback (most recent call last):
  File "/usr/local/bin/VT", line 8, in <module>
    from VideoTester.config import parseArgs, initLogger, VTLOG
  File "/usr/local/lib/python2.7/dist-packages/VideoTester/config.py", line 124, in <module>
    SERVERIP = getIpAddress(SERVERIFACE)
  File "/usr/local/lib/python2.7/dist-packages/VideoTester/config.py", line 87, in getIpAddress
    struct.pack('256s', ifname[:15])
IOError: [Errno 99] Cannot assign requested address

```

Original issue reported on code.google.com by `pav.lith...@gmail.com` on 24 Aug 2014 at 7:32

**Comment by GoogleCodeExporter** [comment]
```
Your interface is down or it hasn't an IP configured.
```

Original comment by `i.uca...@gmail.com` on 4 Sep 2014 at 3:50

**Comment by GoogleCodeExporter** [comment]
```
I have installed videotester on Ubuntu 14.04.
I have an error which as follows..
manu@ubuntu:~/Desktop/VideoTester-0.2$ VT
Traceback (most recent call last):
  File "/usr/local/bin/VT", line 8, in <module>
    from VideoTester.config import parseArgs, initLogger, VTLOG
  File "/usr/local/lib/python2.7/dist-packages/VideoTester/config.py", line 124, in <module>
    SERVERIP = getIpAddress(SERVERIFACE)
  File "/usr/local/lib/python2.7/dist-packages/VideoTester/config.py", line 87, in getIpAddress
    struct.pack('256s', ifname[:15])
IOError: [Errno 19] No such device

Could you please give me solution how to resolve this.I am using videotester 
first time for my project.

Thanks!

```

Original comment by `mungaram...@gmail.com` on 19 Dec 2014 at 4:58

**Comment by GoogleCodeExporter** [comment]
```
"No such device" -> check the interface name.
```

Original comment by `i.uca...@gmail.com` on 21 Dec 2014 at 1:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `i.uca...@gmail.com` on 21 Dec 2014 at 1:19
- Changed state: **Invalid**
