### ISSUE TITLE
Error: Cannot read from the resource (the client)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prathikshetty/video-tester#2]
```
What steps will reproduce the problem?
1.I run the VT server on my Ubuntu system
VT server
2.Run the VT client on the same computer
VT client -g
3.I downloaded the test video and made a directory under the folder 
'VideoTest-0.2'. 

What is the expected output? What do you see instead?
Something correct output

the client GUI was out of response

What version of the product are you using? On what operating system?

VideoTester-0.2
Ubuntu 12.04

Please provide any additional information below.

[2013-01-07 22:43:26,111 VTServer] INFO : XMLRPC Server running at 
192.168.20.203:8000
[2013-01-07 22:43:26,112 VTServer] INFO : Use Control-C to exit
[2013-01-07 22:44:05,443 VTClient] INFO : Client running!
[2013-01-07 22:44:05,444 VTClient] INFO : XMLRPC Server at 192.168.20.203:8000
[2013-01-07 22:44:05,444 VTClient] INFO : Evaluating: video0 + h263 at 128 kbps 
and 25 fps under udp-unicast
[2013-01-07 22:44:05,781 VTServer] INFO : RTSP Server running!
[2013-01-07 22:44:05,783 VTServer] INFO : PID: 26940, 128 kbps - 25 fps server, 
connected clients: 1
[2013-01-07 22:44:05,792 VTClient] INFO : Starting sniffer...
[2013-01-07 22:44:06,291 VTClient] INFO : Pinging...
[2013-01-07 22:44:08,343 VTClient] INFO : Starting GStreamer receiver...
[2013-01-07 22:44:09,151 VTClient] ERROR : GStreamer: MESSAGE_ERROR received
[2013-01-07 22:44:09,152 VTClient] ERROR : 
无法从资源阅读<Chinese>(cannot read from resource<English>)。
[2013-01-07 22:44:09,169 VTClient] INFO : GStreamer receiver stopped

Thank you
```

Original issue reported on code.google.com by `ting.ech...@gmail.com` on 7 Jan 2013 at 2:54

**Comment by GoogleCodeExporter** [comment]
```
Did you place the test video on both the client and the server? It seems a 
misconfiguration problem. Has the key "path" (in "VT.conf", at the server) the 
correct path to the video file? And has the key "video0" the correct file name?

Or maybe there is a problem with file permissions. Has the server read access 
to the test video?
```

Original comment by `i.uca...@gmail.com` on 8 Jan 2013 at 4:48

**Comment by GoogleCodeExporter** [comment]
```
I have try to find something that misconfiguration. The following messages are 
the log on the terminal of the server.
[2013-01-09 22:54:38,173 VTServer] INFO : Use Control-C to exit
[2013-01-09 22:55:15,900 VTServer] INFO : RTSP Server running!
[2013-01-09 22:55:15,902 VTServer] INFO : PID: 10437, 128 kbps - 25 fps server, 
connected clients: 1

(VT:10437): GStreamer-CRITICAL **: gst_poll_set_flushing: assertion `set != 
NULL' failed

(VT:10437): GStreamer-CRITICAL **: gst_poll_set_flushing: assertion `set != 
NULL' failed

(VT:10437): GStreamer-CRITICAL **: gst_poll_set_flushing: assertion `set != 
NULL' failed

(VT:10437): GStreamer-CRITICAL **: gst_poll_set_flushing: assertion `set != 
NULL' failed

and there are two files in the attachment. They are the newest log and the 
VT.conf

```

Original comment by `ting.ech...@gmail.com` on 9 Jan 2013 at 3:01

Attachments:
- [VT.log](https://storage.googleapis.com/google-code-attachments/video-tester/issue-2/comment-2/VT.log)

**Comment by GoogleCodeExporter** [comment]
```
another attachment
```

Original comment by `ting.ech...@gmail.com` on 9 Jan 2013 at 3:01

Attachments:
- [VT.conf](https://storage.googleapis.com/google-code-attachments/video-tester/issue-2/comment-3/VT.conf)

**Comment by GoogleCodeExporter** [comment]
```
I run the video tester both the server and the client on the same laptop.  Is 
that OK?
```

Original comment by `ting.ech...@gmail.com` on 9 Jan 2013 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
"Is that OK?"

Yeah, there shouldn't be any problem with it.

I've managed to reproduce the error. I'm looking for the bug.
```

Original comment by `i.uca...@gmail.com` on 9 Jan 2013 at 3:34

**Comment by GoogleCodeExporter** [comment]
```
Ok. I've got it. This is the syntax that VTServer uses to read the video file 
(VideoTester/gstreamer.py: line 56):

launch = "filesrc location="+self.path+"/"+video+" ! decodebin ! videorate ! 
video/x-raw-yuv,framerate="+str(self.framerate)+"/1 ! "

I've found that the element "decodebin" (it's part of Gstreamer) is unable to 
find a suitable decoder although it is properly installed (ffdec_h264). But 
this only happens with Gstreamer 0.10.36. The version 0.10.35, however, works 
perfectly (with Fedora 16, for example).

Right now, I have no time to seek an alternative to "decodebin", so... Try it 
with Gstreamer 0.10.35 or convert the test video to another format with ffmpeg.

I'll keep this issue opened until this error with the version 0.10.36 is solved.
```

Original comment by `i.uca...@gmail.com` on 9 Jan 2013 at 6:07

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
Original comment by `i.uca...@gmail.com` on 11 Jan 2013 at 10:13
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Hey, 
 I still cannot configure the software on the Ubuntu 12.04. The same reason of running error.
Therefore, I try that on my Fedora 17. But I did not install the 
gstreamer-plugins-bad-nonfree. Because I didn't find the software on the web.
So, Could you give me a list of the software and their version? I found that I 
install the gstreamer on the Fedora 17, but it still are Gstreamer-0.10.36.
The errors are as follow:
[root@echo VideoTester-0.2]# VT client -g
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Gtk-Message: Failed to load module "pk-gtk-module"
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/VideoTester/gui.py", line 336, in onRun
self.measures, self.path = client.run()
File "/usr/lib/python2.7/site-packages/VideoTester/core.py", line 233, in run
from scapy.all import rdpcap
ImportError: No module named scapy.all

From: video-tester
Date: 2013-01-11 18:14
To: ting.echo.yao
Subject: Re: Issue 2 in video-tester: Error: Cannot read from the resource (the 
client)
```

Original comment by `ting.ech...@gmail.com` on 15 Jan 2013 at 12:51

**Comment by GoogleCodeExporter** [comment]
```
Fedora 16 has GStreamer 0.10.35. Try with it. There is a complete list of 
dependencies at the project [http://code.google.com/p/video-tester/ homepage], 
section "Installation".
```

Original comment by `i.uca...@gmail.com` on 15 Jan 2013 at 2:38

**Comment by GoogleCodeExporter** [comment]
```
I have installed all of the software on the Fedora 16, but still error.
The error are from the client

** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/VideoTester/gui.py", line 336, in onRun
    self.measures, self.path = client.run()
  File "/usr/lib/python2.7/site-packages/VideoTester/core.py", line 235, in run
    from VideoTester.gstreamer import RTSPclient
  File "/usr/lib/python2.7/site-packages/VideoTester/gstreamer.py", line 11, in <module>
    from gst.rtspserver import Server, MediaFactory
ImportError: No module named rtspserver

```

Original comment by `ting.ech...@gmail.com` on 17 Jan 2013 at 3:24

**Comment by GoogleCodeExporter** [comment]
```
Oh, sorry, my mistake. I forgot to include one dependency after the last 
update. Run "yum install gstreamer-rtsp-python" and try again.
```

Original comment by `i.uca...@gmail.com` on 17 Jan 2013 at 11:27

**Comment by GoogleCodeExporter** [comment]
```
yes, it is ok now.
But, the client is easy to out of response with nothing outputs. 
I don't know if I do something wrong. There is no error log in the VT.log.

```

Original comment by `ting.ech...@gmail.com` on 17 Jan 2013 at 12:36

**Comment by GoogleCodeExporter** [comment]
```
Could you tell me which file contains the testing result? Because there is no 
error report again, I consider it to correct. But I did not find the file about 
the testing result such as G.1070 quality result or PSNR etc. May be in the 
temp directory?
```

Original comment by `ting.ech...@gmail.com` on 17 Jan 2013 at 1:12

**Comment by GoogleCodeExporter** [comment]
```
The video processing task is very heavy (so I have to improve it). All process 
spends around 1 minute. I recommend using the GUI only to display the results 
(with File->Open). The results are stored under "temp". For example, if you 
test video0 with H.263, 128 kbps, 25 fps and UDP unicast, you can find the 
results under "temp/video0_h263_128_25_udp-unicast".
```

Original comment by `i.uca...@gmail.com` on 17 Jan 2013 at 2:04

**Comment by GoogleCodeExporter** [comment]
```
OK, but I don't know why the result is so wired. And When I using the GUI to 
display the results(File->Open), there is no reasonable file to open and 
display.
In the attachment is the result about I test video0 with H.263,128kbps, 25fps 
and UDP unicast. 

```

Original comment by `ting.ech...@gmail.com` on 17 Jan 2013 at 2:37

Attachments:
- [00_caps.txt](https://storage.googleapis.com/google-code-attachments/video-tester/issue-2/comment-16/00_caps.txt)

**Comment by GoogleCodeExporter** [comment]
```
There should be more files. Can you attach the VT.log for this run?
```

Original comment by `i.uca...@gmail.com` on 17 Jan 2013 at 3:27

**Comment by GoogleCodeExporter** [comment]
Original comment by `ting.ech...@gmail.com` on 17 Jan 2013 at 3:36

Attachments:
- [VT.log](https://storage.googleapis.com/google-code-attachments/video-tester/issue-2/comment-18/VT.log)
- [00.h263](https://storage.googleapis.com/google-code-attachments/video-tester/issue-2/comment-18/00.h263)

**Comment by GoogleCodeExporter** [comment]
```
"Keyboard interrupt". You are stopping the client too early. ;-) Be patient, 
give it time. As I said, around 1 minute.
```

Original comment by `i.uca...@gmail.com` on 17 Jan 2013 at 3:42

**Comment by GoogleCodeExporter** [comment]
```
Now I found the message printed by the client:
[2013-01-21 13:43:50,620 VTClient] INFO : Client running!
[2013-01-21 13:43:50,621 VTClient] INFO : XMLRPC Server at 192.168.89.130:8000
[2013-01-21 13:43:50,621 VTClient] INFO : Evaluating: video0 + h264 at 128 kbps 
and 25 fps under udp-unicast
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
[2013-01-21 13:43:52,887 VTClient] INFO : Starting sniffer...
[2013-01-21 13:43:53,387 VTClient] INFO : Pinging...
[2013-01-21 13:43:55,404 VTClient] INFO : Starting GStreamer receiver...
[2013-01-21 13:44:08,736 VTClient] INFO : GStreamer receiver stopped
And I have checked the output file in the directory /temp. They are the same as 
I attached in last comment.

PS. Could you attach me about the correct running results?
```

Original comment by `ting.ech...@gmail.com` on 21 Jan 2013 at 1:48

**Comment by GoogleCodeExporter** [comment]
```
This is a normal log. Check the attachment.
```

Original comment by `i.uca...@gmail.com` on 21 Jan 2013 at 2:33

Attachments:
- [VT.log](https://storage.googleapis.com/google-code-attachments/video-tester/issue-2/comment-21/VT.log)

**Comment by GoogleCodeExporter** [comment]
```
I still found that the log stopped to output any messages and just like the 
client was out of response.
[2013-01-21 13:43:52,835 VTServer] INFO : RTSP Server running!
[2013-01-21 13:43:52,836 VTServer] INFO : PID: 2242, 128 kbps - 25 fps server, 
connected clients: 1
[2013-01-21 13:43:52,887 VTClient] INFO : Starting sniffer...
[2013-01-21 13:43:53,387 VTClient] INFO : Pinging...
[2013-01-21 13:43:55,404 VTClient] INFO : Starting GStreamer receiver...
[2013-01-21 13:44:08,736 VTClient] INFO : GStreamer receiver stopped
[2013-01-21 14:47:05,803 VTClient] WARNING : Keyboard interrupt!
Is that because I did not wait the client for enough time?

```

Original comment by `ting.ech...@gmail.com` on 21 Jan 2013 at 2:50

**Comment by GoogleCodeExporter** [comment]
```
13:44 to 14:47? Mmmh... Definitely, this is not the reason. Are you running the 
client and the server at the same machine? Are you using "iface=eth0" or 
similar at VT.conf? Try putting "iface=lo".
```

Original comment by `i.uca...@gmail.com` on 21 Jan 2013 at 3:11

**Comment by GoogleCodeExporter** [comment]
```
Yes. I am running the client and the server at the same client. Actually, I run 
the client on one terminal and run the server on the other terminal on my 
virtual machine.
Yes, I am.
I will try it.
```

Original comment by `ting.ech...@gmail.com` on 21 Jan 2013 at 3:20

**Comment by GoogleCodeExporter** [comment]
```
OK, finally, I have run the videotester successfully.
Thank you very much for helping me so patiently. :-)
```

Original comment by `ting.ech...@gmail.com` on 21 Jan 2013 at 3:29

**Comment by GoogleCodeExporter** [comment]
```
Great! Thank you for your feedback!
```

Original comment by `i.uca...@gmail.com` on 21 Jan 2013 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
What is the procedure to use Video-Tester use 
```

Original comment by `vijaykan...@gmail.com` on 20 Mar 2013 at 11:27

**Comment by GoogleCodeExporter** [comment]
```
VT server
Traceback (most recent call last):
  File "/usr/local/bin/VT", line 8, in <module>
    from VideoTester.config import parseArgs, initLogger, VTLOG
  File "/usr/local/lib/python2.7/site-packages/VideoTester/config.py", line 124, in <module>
    SERVERIP = getIpAddress(SERVERIFACE)
  File "/usr/local/lib/python2.7/site-packages/VideoTester/config.py", line 87, in getIpAddress
    struct.pack('256s', ifname[:15])

```

Original comment by `vijaykan...@gmail.com` on 20 Mar 2013 at 12:08

**Comment by GoogleCodeExporter** [comment]
```
Server is running but while running Client i am getting this error
Traceback (most recent call last):
  File "/usr/local/bin/VT", line 13, in <module>
    initLogger(args)
  File "/usr/local/lib/python2.7/site-packages/VideoTester/config.py", line 34, in initLogger
    fh = logging.FileHandler(TEMP + 'VT.log')
  File "/usr/local/lib/python2.7/logging/__init__.py", line 893, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python2.7/logging/__init__.py", line 912, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: 
'/home/VIJAY/VideoTester-0.2/temp/temp/VT.log'


```

Original comment by `vijaykan...@gmail.com` on 20 Mar 2013 at 12:25

**Comment by GoogleCodeExporter** [comment]
```
Issue 4 has been merged into this issue.
```

Original comment by `i.uca...@gmail.com` on 18 Nov 2013 at 11:04

**Comment by GoogleCodeExporter** [comment]
```
Issue 4 has been merged into this issue.
```

Original comment by `i.uca...@gmail.com` on 26 Nov 2013 at 9:13
