### ISSUE TITLE
GStreamer: MESSAGE_ERROR received

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prathikshetty/video-tester#4]
```
What steps will reproduce the problem?
1.I run the VT server on my Ubuntu system
VT server
2.Run the VT client on the same computer
sudo VT client -g
3.I downloaded the test video and made a directory named 'VideoSample' under 
the folder 'VideoTest-0.2'. 

What is the expected output? What do you see instead?
No error message in log and all necessary files are generated.
I got "GStreamer: MESSAGE_ERROR received" twice on log and stucked at "Starting 
packet parser..". A few files are generated (refer attachment) but no .pkl 
files.
(run this for a few times using different videos and codec, but still get the 
same result)

What version of the product are you using? On what operating system?
VideoTester-0.2
Ubuntu 12.04.3

Please provide any additional information below.
As attached.

Thank you

```

Original issue reported on code.google.com by `irdaros...@gmail.com` on 13 Nov 2013 at 5:33
- Merged into: #2

Attachments:
- [errorlogs_131113](https://storage.googleapis.com/google-code-attachments/video-tester/issue-4/comment-0/errorlogs_131113)
- [Screenshot - video tester gui.png](https://storage.googleapis.com/google-code-attachments/video-tester/issue-4/comment-0/Screenshot - video tester gui.png)
- [Screenshot - generated_02_files.png](https://storage.googleapis.com/google-code-attachments/video-tester/issue-4/comment-0/Screenshot - generated_02_files.png)

**Comment by GoogleCodeExporter** [comment]
```
It seems the GStreamer RTSP server is not working well. Check these 
dependencies, please:

- GStreamer 0.10.35 with Python bindings.
- GStreamer plugins: base, good, ugly, bad.
- GStreamer FFmpeg plugins.
- GStreamer RTSP server 0.10.8 (at least) with Python bindings. 
```

Original comment by `i.uca...@gmail.com` on 14 Nov 2013 at 2:34

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your response. I also received this error message on server's side:
[2013-11-18 10:57:19,428 VTServer] INFO : XMLRPC Server running at 
192.168.14.57:8000
[2013-11-18 10:57:19,428 VTServer] INFO : Use Control-C to exit
[2013-11-18 10:57:51,158 VTServer] INFO : RTSP Server running!
[2013-11-18 10:57:51,158 VTServer] INFO : PID: 3696, 128 kbps - 25 fps server, 
connected clients: 1

(VT:3696): GStreamer-CRITICAL **: gst_poll_set_flushing: assertion `set != 
NULL' failed

(VT:3696): GStreamer-CRITICAL **: gst_poll_set_flushing: assertion `set != 
NULL' failed

(VT:3696): GStreamer-CRITICAL **: gst_poll_set_flushing: assertion `set != 
NULL' failed

(VT:3696): GStreamer-CRITICAL **: gst_poll_set_flushing: assertion `set != 
NULL' failed

----------------
I attached the list of dependencies that have been installed. Please let me 
know if there are any dependencies missing.

And these are among Python dependencies (with versions) installed:
python-scapy        2.2.0-1
python-numpy        1:1.6.1-6ubuntu1
python-opencv       2.3.1-7
python-gst0.10      1.10.22-3ubuntu0.1 (generic media-playing framework (Python 
binding))
python-gst0.10-rtsp 0.10.8-3 (GStreamer RTSP server plugin (Python binding))
python-wxmpl        2.0.0-2 (painless matplotlib embedding in wxPython)
python-wxgtk2.8     2.8.12.1-6ubuntu2 (wxWidgets Cross-platform C++ GUI toolkit 
(wxPython))
python-wxversion    2.8.12.1-6ubuntu2


Thanks again


```

Original comment by `irdaros...@gmail.com` on 18 Nov 2013 at 2:50

**Comment by GoogleCodeExporter** [comment]
```
Attached is the gstreamer dependencies
```

Original comment by `irdaros...@gmail.com` on 18 Nov 2013 at 3:00

Attachments:
- [gstreamer_plugins2.png](https://storage.googleapis.com/google-code-attachments/video-tester/issue-4/comment-3/gstreamer_plugins2.png)

**Comment by GoogleCodeExporter** [comment]
```
It's clear that the problem comes from GStreamer. It seems that you have 
installed all the packages needed. However, there is a known issue (related to 
the element "decodebin", I think, but I've hadn't time to fix it) with 
GStreamer versions above 0.10.35 (see this comment: 
http://code.google.com/p/video-tester/issues/detail?id=2#c6)

Apparently, you have the version 0.10.36 (check it with the command "apt-cache 
showpkg libgstreamer0.10"). This means that you have to downgrade GStreamer in 
order to run Video-Tester (sorry; or you could help me debug this issue ;-) ).
```

Original comment by `i.uca...@gmail.com` on 18 Nov 2013 at 11:04
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
Thank you very much for your guidance. I managed to run the program 
successfully after downgrading the GStreamer. However, it seems that only 
running via TCP works well with error-free results, no matter what kind of 
codec was selected.
But when I chose udp-unicast or udp-multicast, the following error message 
appeared on client's terminal:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/VideoTester/gui.py", line 336, in onRun
    self.measures, self.path = client.run()
  File "/usr/local/lib/python2.7/dist-packages/VideoTester/core.py", line 265, in run
    packetdata = sniffer.parsePkts()
  File "/usr/local/lib/python2.7/dist-packages/VideoTester/sniffer.py", line 126, in parsePkts
    self.__normalize()
  File "/usr/local/lib/python2.7/dist-packages/VideoTester/sniffer.py", line 333, in __normalize
    seq = self.sequences[0]
IndexError: list index out of range

Can you please help me sort this out? Thanks again.

```

Original comment by `irdaros...@gmail.com` on 26 Nov 2013 at 4:47

**Comment by GoogleCodeExporter** [comment]
```
I have to code some kind of well formatted output for this exception. A "list 
index out of range" error in the sniffer means that no packets were received. A 
firewall or NAT would probably be blocking the UDP stream.
```

Original comment by `i.uca...@gmail.com` on 26 Nov 2013 at 9:13

**Comment by GoogleCodeExporter** [comment]
```
Already settled that part and it seems that everything works well now. =D
The processing on the client side is quite slow, need to upgrade the RAM i 
guess..

Thanks again for your help and all the quick responses. Really appreciate them. 
Hats off to you..
```

Original comment by `irdaros...@gmail.com` on 27 Nov 2013 at 5:22

**Comment by prathikshetty** [comment]
Hi,

I'm using videotester2 in ubuntu 14.04 PC. Im getting same error as mentioned in this issue ( Please refer VT_error.png attachment) . You have mentioned the solution as " Downgrade the Gstreamer". Please let me know , how can I downgrade the Gstreamer.  I have already installed gstreamer0.10-tools (0.10.36-1ubuntu1). But there is no Gstreamer package gstreamer0.10-tools (0.10.35).
Please help.
![vt_error](https://cloud.githubusercontent.com/assets/18167181/14142504/cb43a448-f6a3-11e5-8b30-07e35ea83402.png)

Thanks in advance.
