### ISSUE TITLE
Enter one-line summary

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prathikshetty/video-tester#5]
```
What steps will reproduce the problem?
1.sudo python setup.py install

2.VT client
3.

What is the expected output? What do you see instead?
i expected the complete output.
but i see errors in the client side but the server part is running

What version of the product are you using? On what operating system?

video tester 0.2
ubuntu 12.04
Please provide any additional information below.
i see import errors

aparna@aparna-Satellite-C850:~/PROJECT/video-tester$ sudo VT client
[2014-01-22 16:00:40,309 VTClient] INFO : Client running!
[2014-01-22 16:00:40,310 VTClient] INFO : XMLRPC Server at 192.168.173.35:8000
[2014-01-22 16:00:40,310 VTClient] INFO : Evaluating: video0 + h264 at 128 kbps 
and 25 fps under udp-unicast
Traceback (most recent call last):
  File "/usr/local/bin/VT", line 40, in <module>
    client.run()
  File "/usr/local/lib/python2.7/site-packages/VideoTester/core.py", line 235, in run
    from VideoTester.gstreamer import RTSPclient
  File "/usr/local/lib/python2.7/site-packages/VideoTester/gstreamer.py", line 7, in <module>
    from gobject import MainLoop
ImportError: No module named gobject

i have installed all the dependencies including rtspserver and gstreamer can 
you provide the solutions pls...





```

Original issue reported on code.google.com by `aparnay...@gmail.com` on 22 Jan 2014 at 11:18

**Comment by GoogleCodeExporter** [comment]
```
Try it installing python-gobject and/or python-gobject-2.
```

Original comment by `i.uca...@gmail.com` on 22 Jan 2014 at 11:26

**Comment by GoogleCodeExporter** [comment]
```
hai..
i have installed the gobject using apt-get install python-gob*

but it showing the same error 
root@aparna-Satellite-C850:~/video-tester# VT client
[2014-01-23 09:56:28,553 VTClient] INFO : Client running!
[2014-01-23 09:56:28,554 VTClient] INFO : XMLRPC Server at 192.168.173.35:8000
[2014-01-23 09:56:28,554 VTClient] INFO : Evaluating: video0 + h264 at 128 kbps 
and 25 fps under udp-unicast
Traceback (most recent call last):
  File "/usr/local/bin/VT", line 40, in <module>
    client.run()
  File "/usr/local/lib/python2.7/site-packages/VideoTester/core.py", line 235, in run
    from VideoTester.gstreamer import RTSPclient
  File "/usr/local/lib/python2.7/site-packages/VideoTester/gstreamer.py", line 7, in <module>
    from gobject import MainLoop
ImportError: No module named gobject

```

Original comment by `aparnay...@gmail.com` on 23 Jan 2014 at 4:28

**Comment by GoogleCodeExporter** [comment]
```
pls replyyy
```

Original comment by `aparnay...@gmail.com` on 23 Jan 2014 at 5:37

**Comment by GoogleCodeExporter** [comment]
```
Check this link: 
http://askubuntu.com/questions/279866/python-module-not-found-after-manual-insta
ll
```

Original comment by `i.uca...@gmail.com` on 23 Jan 2014 at 9:02

**Comment by GoogleCodeExporter** [comment]
```
tanku for the reply. but i dnt get it i  run the sudo apt-get update && sudo 
apt-get dist- and my sys path is 

aparna@aparna-Satellite-C850:~$  python -c "import sys; print sys.path" 
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', 
'/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', 
'/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', 
'/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PIL', 
'/usr/lib/python2.7/dist-packages/gst-0.10', 
'/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', 
'/usr/lib/python2.7/dist-packages/ubuntu-sso-client', 
'/usr/lib/python2.7/dist-packages/ubuntuone-client', 
'/usr/lib/python2.7/dist-packages/ubuntuone-control-panel', 
'/usr/lib/python2.7/dist-packages/ubuntuone-couch', 
'/usr/lib/python2.7/dist-packages/ubuntuone-installer', 
'/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol']



can you help me .what should i do?? if you want to know other files pls inform 
me.

```

Original comment by `aparnay...@gmail.com` on 23 Jan 2014 at 10:04

**Comment by GoogleCodeExporter** [comment]
```
If you have installed python-gobject-2 and it is not yet working, it seems to 
be some kind of problem with paths. So this is not a bug and I can't help you. 
I'm sorry, but simply I can't keep track of all the dependency names in all 
distros and all their specific problems.

You should be able to find some help in Ubuntu-related forums.
```

Original comment by `i.uca...@gmail.com` on 23 Jan 2014 at 10:36
- Changed state: **Invalid**
